#!/bin/bash

set -x

echo Installing ArgoCD...

kubectl get ns argocd || kubectl create ns argocd

kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
