#!/bin/bash

set -x

AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
AWS_REGION=$(aws configure get region)

AWS_PROFILE=$(aws configure get profile)

echo Installing ArgoCD...

kubectl get ns argocd || kubectl create ns argocd

kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

pushd scripts

export GITHUB_EVENT_PATH=$(pwd)/event.json
export GITHUB_SHA=$(git rev-parse remotes/origin/master)

kubectl get ns prenv-apps || kubectl create ns prenv-apps

go run .. apply
